library(readr)
BIC <- read_csv("BIC.csv")
mean(BIC$`FINE AMOUNT`)
mean(BIC$`MAXIMUM FINE`)
median(BIC$`FINE AMOUNT`)
median(BIC$`MAXIMUM FINE`)
sd(BIC$`FINE AMOUNT`)
sd(BIC$`MAXIMUM FINE`)
var(BIC$`FINE AMOUNT`)
var(BIC$`MAXIMUM FINE`)